### ISSUE TITLE
does not support text items

### ISSUE THREAD

**Issue by vimperatorluo** [oehhar/tksvg#15]
I use pikchr(https://pikchr.org/) to generate svg file, tksvg can't display text items.
should be 

![image](https://user-images.githubusercontent.com/85391102/120887044-538c9380-c5e0-11eb-9b30-e9d0e6835cdb.png)

but got 
![tst](https://user-images.githubusercontent.com/85391102/120887209-11b01d00-c5e1-11eb-8bbf-ca7b82c4b060.png)

**Comment by auriocus** [comment]
Text is not supported, because it is a big task to do text rendering which cannot be done properly without a large collection of support libraries for font handling, typesetting, hyphenation etc.

**Comment by oehhar** [comment]
Dear vimperatorluo,
yes, thank you for the comment. You observation is correct and intended.
I invite you to look on the wiki page:

https://wiki.tcl-lang.org/page/tksvg

Best regards,
Harald
