### ISSUE TITLE
Protect against version 8.7

### ISSUE THREAD

**Issue by bll123** [oehhar/tksvg#17]
I recommend that the pkgIndex.tcl file be changed to have:

if { [package vcompare 8.7 [info tclversion]] > 0 } {
   ...
}

to protect against inclusion in Tk 8.7 and later.
There is a possibility that the multiple inclusion can cause corruption in 8.7.

**Comment by oehhar** [comment]
Yes, great idea ! I tried to check Tk version instead Tcl, as it is Tk related.
Do you agree with commit [59833d3] ?

I tested it with success on Windows with the nmake build method. I would appreciate, if you could check the TEA one.
Package index file is magic to me, sorry.

Thank you,
Harald

**Comment by oehhar** [comment]
Brad,
I had another idea. We could make a "package require tksvg" a succeeding no-op.
So, scripts may do a "package require tksvg" in Tk 8.6 and Tk8.7.

What do you think ?
Harald

**Comment by bll123** [comment]
There's an issue.  It looks like the package management system is processing the pkgIndex.tcl file before
Tk is loaded.   This happened with both 8.6.10 and 8.7. 

I agree that the Tk version should be tested if possible (as there are noises being made about making
the version numbers no longer match).

With this code, the catch statement works, and the first error message is gone.

Ah, I see the issue I was running into.  The 'versions' sub-command returns all versions found.

```
% package version Tk
8.6.10 8.7a4
```

**Assuming** they're in order, low to high:
`llindex [package versions Tk] end`
will work.

```
if { [catch {package present Tk}] } { return }
if { [package vcompare 8.6.20 [lindex [package versions Tk] end]] <= 0 } { return }
package ifneeded tksvg 0.7.1 \
    [list load [file join $dir libtksvg0.7.1.so] tksvg]
```

Well, while 'package vcompare' is technically correct according to the Tcl version scheme, it isn't very useful.  Sigh.
I suppose the vcompare could compare against version 8.6.20.
I think that's what I will do when I get to changing my Tcl version comparisons to Tk version comparisons.
The programmer must know to put in a strange version number if they ever work with pre-releases.

```
% package vcompare 8.7 8.7a4
1
% package vcompare 8.7a4 8.7a1
1
% package vcompare 8.7a1 8.7
-1
```


**Output from original pkgIndex.tcl file:**
```
bll-g7:bll$ $HOME/s/ballroomdj/linux/64/tcl/bin/tclsh    # 8.7
% puts $::auto_path
//zipfs:/lib/tcl/tcl_library //zipfs:/lib/tcl /home/bll/s/ballroomdj/linux/64/tcl/lib
% lappend ::auto_path /home/bll/local/lib
//zipfs:/lib/tcl/tcl_library //zipfs:/lib/tcl /home/bll/s/ballroomdj/linux/64/tcl/lib /home/bll/local/lib
% package require Tk
error reading package index file /home/bll/local/lib/tksvg0.7.1/pkgIndex.tcl: expected version number but got ""
8.7a4
% package require tksvg
# the following error message happens due to some sort of mixing of 8.6.10 and 8.7.
# the auto path appended above points to the 8.6.10 lib directory, and there are other 8.6.10 files there.
# when I moved the tksvg package to a separate library directory, it worked properly.
error reading package index file /home/bll/local/lib/tksvg0.7.1/pkgIndex.tcl: expected version number but got "8.6.10 8.7a4"
can't find package tksvg
% package present tksvg
package tksvg is not present
% 
```

**Comment by bll123** [comment]
A succeeding no-op would be fine.  I have no issue with that.
Might be slightly confusing when someone reports issues and claim version x.y when they are using Tk 8.7+

**Comment by bll123** [comment]
I believe this works without worrying about 'package versions' ordering.
I can't do anything about the 'package vcompare' weirdness, so 8.6.99 is probably the best choice.

```
if { [catch {package present Tk}] } { return }
if { [package vcompare 8.6.99 $::tk_version] <= 0 } { return }
package ifneeded tksvg 0.7.1 \
    [list load [file join $dir libtksvg0.7.1.so] tksvg]
```

**Comment by bll123** [comment]
It occurs to me that it may not be safe to do a 'return' from within a pkgIndex.tcl file.
(what is the code returning from?)
Probably better to change it to:

```
if { ! [catch {package present Tk}] } { 
  if { [package vcompare 8.6.99 $::tk_version] > 0 } { 
    package ifneeded tksvg 0.7.1 \
      [list load [file join $dir libtksvg0.7.1.so] tksvg]
  }
}
```

::tk_version has:
```
% puts $::tk_version
8.6
```

If it can be trusted that ::tk_version is always the major version number, then the code would be better as:

```
if { ! [catch {package present Tk}] } { 
  if { [package vcompare 8.7 $::tk_version] >= 0 } { 
    package ifneeded tksvg 0.7.1 \
      [list load [file join $dir libtksvg0.7.1.so] tksvg]
  }
}
```

**Comment by auriocus** [comment]
Isn't there a different way to make this unproblematic? For instance, Tk has native PNG support from 8.6 in much of the same way, by an additional image photo handler. Still, TkImg can be loaded into 8.6 and then the handler from TkImg is used instead of the built-in one. Why does it work with TkImg?

**Comment by bll123** [comment]
Good question.

I wrote:
> There is a possibility that the multiple inclusion can cause corruption in 8.7.
I had a segmentation violation on MacOS, and it seems to have disappeared after removing the 'package require tksvg'.
This is just a possibility, a hypothesis, a maybe, a guess, not a certainty.

**Comment by oehhar** [comment]
As brad unfortunately left us, there is no follow-up. So, I close the bug.
