### ISSUE TITLE
Is tksvg 0.9 still claiming to be 0.8?

### ISSUE THREAD

**Issue by bagnongithub** [oehhar/tksvg#18]
In configure:

# Identity of this package.
PACKAGE_NAME='tksvg'
PACKAGE_TARNAME='tksvg'
PACKAGE_VERSION='0.8'
PACKAGE_STRING='tksvg 0.8'
PACKAGE_BUGREPORT=''
PACKAGE_URL=''

**Comment by oehhar** [comment]
Yes, sorry for that. I hope it is corrected.
Thanks again,
Harald
