### ISSUE TITLE
placing elements of image into top-left corner makes image appear black

### ISSUE THREAD

**Issue by Anonymous-Kingg** [oehhar/tksvg#20]
yeah pretty self explanatory.

what the thing is supposed to look like 
https://drive.google.com/file/d/13CT8g9gPqKBvJ5-3ouv7JM_Pf-Vn5kLL/view?usp=share_link

what it ends up looking like 
https://drive.google.com/file/d/1iSBjp55cQtIhZehwuUSGQExRtZ2TP2CM/view?usp=share_link

**Comment by oehhar** [comment]
If you have any issues with svg file rendering, please remark that nanosvg has a lot of limitations on the svg file.
See the project "svgnano" on github to get more information.

**Comment by Anonymous-Kingg** [comment]
svgnano is not a project on github, at least as far as i can see

**Comment by oehhar** [comment]
https://github.com/memononen/nanosvg

**Comment by Anonymous-Kingg** [comment]
i cant find this issue with anything else that uses nanosvg, do you have any idea as to what i can do?

**Comment by oehhar** [comment]
Here, you have some hints how to create the svg files compatible to nanosvg:

https://wiki.tcl-lang.org/page/SVG

**Comment by Anonymous-Kingg** [comment]
ok fixed it by exporting files from illustrator using a script instead of the normal export
thanks for trying to help
