### ISSUE TITLE
Gradient Attributes don't work

### ISSUE THREAD

**Issue by ThingamabobsCoding** [oehhar/tksvg#22]
Hello [this issue](https://stackoverflow.com/q/74797469/13629335) seems to be still reproducible with 0.13

The data to reproduce it is as follows:
```
<svg width="120" height="240" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="Gradient1">
      <stop offset="0%" stop-color="red" />
      <stop offset="50%" stop-color="black" stop-opacity="0" />
      <stop offset="95%" stop-color="blue" />
    </linearGradient>
    <linearGradient id="Gradient2" x1="0" x2="0" y1="0" y2="1">
      <stop offset="0%" stop-color="red" />
      <stop offset="50%" stop-color="black" stop-opacity="0" />
      <stop offset="95%" stop-color="blue" />
    </linearGradient>
  </defs>

  <rect id="rect1" x="10" y="10" rx="15" ry="15"
      width="100" height="100" fill="url(#Gradient1)"/>
  <rect
    x="10"
    y="120"
    rx="15"
    ry="15"
    width="100"
    height="100"
    fill="url(#Gradient2)" />
</svg>
```

**Comment by oehhar** [comment]
It is by purpose. Gradients is one of the not supported features.

You may look to other svg renderers, if this is important for you.

Here is the parent project:

https://github.com/memononen/nanosvg

You may also look to the wiki page with some hints:

https://wiki.tcl-lang.org/svg

Take care,
Harald

**Comment by oehhar** [comment]
Well, I might be wrong. I use gradients with Inkscape, and they work.

When I look into the file, I see:

```
    <linearGradient
       y2="16"
       x2="32"
       y1="16"
       x1="0"
       gradientTransform="translate(0,1.1754297e-4)"
       gradientUnits="userSpaceOnUse"
       id="linearGradient3874"
       xlink:href="#linearGradient4145"
       inkscape:collect="always" />
    ....
    <rect
       style="fill:url(#linearGradient3874);fill-opacity:1;fill-rule:evenodd;stroke:none;display:inline"
       id="rect3965"
       width="32"
       height="32"
       x="0"
       y="0.00012207031"
       transform="translate(0,1020.3622)" />
```

We really try to fit to the upstream project.
But there are a lot of pull requests open.
I am not sure.
Auriocus may have included some of them.

But this is exactly what will be in Tk 8.7.

Sorry,
Harald

**Comment by ThingamabobsCoding** [comment]
No need to apologize, 
I'm really happy the stated features in [TIP 507](https://core.tcl-lang.org/tips/doc/trunk/tip/507.md) are still in progress and not off of the table.

Thanks for taking care and your effort into this project.
Looking forward to use it once it's done.

Best regards, 
Marko
