### ISSUE TITLE
Small copyright glitch

### ISSUE THREAD

**Issue by olebole** [oehhar/tksvg#24]
I am currently packaging tksvg for Debian ([Debian#1078064](https://bugs.debian.org/1078064); https://salsa.debian.org/tcltk-team/tksvg). For this, I need to review the license information. What I am wondering is that the `license.term` file starts with https://github.com/oehhar/tksvg/blob/511787a06b23e196684817c4bf7c5ec31ca29afc/license.terms#L1-L3

Is the package really partially copyrighted by the Regents of the University of California and Sun Microsystems? ActiveState is mentioned in `tcl.m4`.

**Comment by oehhar** [comment]
Ole,
thank you for the message, I appreciate !
The licence file is IMHO verbatim copied from tk.
The only people who have worked on this file is Mikko (from nanosvg), Christian (author of the TCL interface) and a bit myself.
I suppose, we could change this and put only those people in.

This distribution includes svgnano with this licence file: [https://github.com/memononen/nanosvg/blob/master/LICENSE.txt].

@auriocus : do you think, we may change the licence file to contain Mikko and you as copyright holder?
I think, that would be a good step.

Thank you all,
Harald

**Comment by oehhar** [comment]
See commit [d6593b0d](https://github.com/oehhar/tksvg/commit/d6593b0df3cd0ee5251d344bf86d7ad5703d18cb).
The contributors are now named.
The contained TCL make system has its folder with readme and copyright.
I think, this may stay as it is.

Thanks for all,
Harald

**Comment by oehhar** [comment]
@olebole : are you happy with the change ?
I see, the issue is closed. This was you?

Thanks for all ! A visit in Potsdam is still pending...

Take care,
Harald

**Comment by olebole** [comment]
Yep, that looks nice! Thank you for the update!
